version: '3.8'

services:
  web:
    image: ghcr.io/efrei-craft/efrei-craft-web:master
    container_name: efrei-craft-web
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`efreicraft.fr`)"
      - "traefik.http.routers.website.entrypoints=websecure"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
