version: '3.8'

services:
  web:
    image: ghcr.io/efrei-craft/efrei-craft-web:master
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.efrei-craft-web.rule=Host(`efreicraft.fr`)"
        - "traefik.http.routers.efrei-craft-web.entrypoints=websecure"
        - "traefik.http.services.efrei-craft-web.loadbalancer.server.port=80"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
